version: '3.9'
services:
  gotrue:
    image: gotrue
    ports:
      - '9999:9999'
    env_file:
      - gotrue.env
    depends_on:
      - postgres
  postgres:
    image: gotrue_postgres
    ports:
      - '5432:5432'
    volumes:
      - gotrue_postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - DB_NAMESPACE=auth
volumes:
  gotrue_postgres_volume: